import dash
from dash import dcc, html
import dash_bootstrap_components as dbc
from assets import dropdown_values
from dash_bootstrap_templates import ThemeChangerAIO, template_from_url


def build_header_bar(app):
    return dbc.Navbar(color="secondary", className="banner", sticky="top", 
                      children=[
                            build_banner(app),
                            build_intervals_div()
                        ])
    
    
def build_banner(app):
    suggestions = ["Tata Consultancy Services", "options", "as", "suggestions"]; # generated by, i.e. query to db
    options = [html.Option(value=word) for word in suggestions]
    
    return dbc.Container(id="header_container", children=[
                html.Img(id="banner_logo", src=app.get_asset_url("logo.PNG")),
                build_tabs(),
                
                html.Datalist(id='list_suggested_inputs', children=options),
                dbc.Col(dbc.Input(type="text", placeholder="Search a Company", list="list_suggested_inputs"), width=3),
                dbc.Col([
                    dbc.Button("Search", color="primary", className="ms-2", n_clicks=0),
                    dbc.Button("Log Out", color="primary", className="ms-2", n_clicks=0),],
                    width="auto",
                ),
                # ThemeChangerAIO(aio_id="theme", 
                #                 button_props={"color": "primary", "style": {"height": "auto", "width": "5vw"}},
                #                 radio_props={"value": dbc.themes.CERULEAN})
            ])


def build_tabs():
    
    return html.Div(className="header_tabs", children=[
                dbc.Nav(pills=True, children=[
                    dbc.NavItem(dbc.NavLink(f"{page['name']}", id=page["module"],  href=page["relative_path"], active=False))
                    for page in dash.page_registry.values()]),
                ])
    
    
def build_intervals_div():
    return html.Div(id='interval_div', children=[
        dcc.Interval(id="i1", interval=1 * 1000, n_intervals=0),
        dcc.Interval(id="i2", interval=2 * 1000, n_intervals=0),
        dcc.Interval(id="i5", interval=5 * 1000, n_intervals=0),
        dcc.Interval(id="i60", interval=60 * 1000, n_intervals=0),
    ])


